import { Reg, Bold, ExBold, Med } from "@/assest/next-fonts";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${Reg.variable} ${Med.variable} ${Bold.variable} ${ExBold.variable} font-sans`}
      >
        <main className="relative flex-col min-h-screen bg-white-app">
          {children}
        </main>
      </body>
    </html>
  );
}
